{{ if and .Values.kafka.enabled .Values.kafka.authentication -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kafka.authentication.passwordSecret.secretName }}
type: Opaque
data:
  {{ .Values.kafka.authentication.passwordSecret.password }} : {{ .Values.kafka.authentication.passwordSecret.password | sha1sum | b64enc | quote }}
{{- end }}