{{- $namespace := .Release.Namespace -}}
{{ if and .Values.kafka.enabled .Values.kafka.topics }}
{{- range $key,$val := .Values.kafka.topics }}
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ $val.name }}
  namespace: {{ $namespace }}
spec:
  partitions: {{ $val.partitions }}
  replicas: {{ $val.replicas }}
---
{{- end }}
{{- end }}